<?php
$title = 'Parametres de mon compte';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'user',
    array(
        'action' => 'settings'
    )
));
$form->setAttribute('method', 'post');
echo $this->form ()->openTag ( $form );

?>
<dl class="zend_form">
	<?php echo $this->formHidden($form->get('user_id')); ?>
	<dd><?php
	echo $this->formRow ( $form->get ( 'surname' ) );
	?></dd>
	<dd><?php
	echo $this->formRow ( $form->get ( 'firstname' ) );
	?></dd>
	<dd><?php
	echo $this->formRow ( $form->get ( 'password' ) );
	?></dd>
	<dd><?php
	echo $this->formRow ( $form->get ( 'email' ) );
	?></dd>
	<dd><?php
	echo $this->formRow ( $form->get ( 'phonenumber' ) );
	?></dd>
	<dd><?php
	echo $this->formSubmit ( $form->get ( 'submit' ) );
	?></dd>
</dl>

<?php echo $this->form()->closeTag(); ?>