<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Qvmrest\Module'                        => __DIR__ . '/Module.php',
    'Qvmrest\Controller\QvmrestController' => __DIR__ . '/src/Qvmrest/Controller/QvmrestController.php',
    'QvmrestTest\Framework\TestCase'        => __DIR__ . '/tests/Qvmrest/Framework/TestCase.php',
    'QvmrestTest\SampleTest'                => __DIR__ . '/tests/Qvmrest/SampleTest.php',
);
