<?php
$form = $this->form;
echo $this->form ()->openTag ( $form );
?>
<div class="row-fluid">
	<div class="span9">
		<h1>Mes prochains &eacutev&eacutenements</h1>
		<table class="table">
			<?php
			foreach ( $upcomingParticipatings as $upcomingParticipating ) :
				?>
				 <tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
					<td><?php echo $this->escapeHtml($upcomingParticipating->title);?></td>
					<td><a href="<?php echo $this->url('activity', array('action'=>'detailEvent', 'id' => $upcomingParticipating->id_event));?>" >
							<?php  echo strftime("%d/%m/%Y a %Hh%M", strtotime($upcomingParticipating->date) ); ?></a>
					</td>
				<td><?php echo $this->formRow ( $form->get ( 'voteEvenement' )->setAttribute('value',$upcomingParticipating->vote) ).'&nbsp;'; echo $this->formRow ( $form->get ( 'submit' ));?></td>
				</tr>
				<?php 
			endforeach; ?>
		</table>
		
		<h1>Mes &eacutev&eacutenements en attente de vote</h1>
		<table class="table">
			<?php
			foreach ( $pendingParticipatingsLimit as $pendingParticipating ) :
				?>
				 <tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
					<td><?php echo $this->escapeHtml($pendingParticipating->title);?></td>
					<td><a href="<?php echo $this->url('activity', array('action'=>'detailEvent', 'id' => $pendingParticipating->id_event));?>" >
			<?php  echo strftime("%d/%m/%Y a %Hh%M", strtotime($pendingParticipating->date) ); ?></a>
		</td>
					<td><?php echo $this->formRow ( $form->get ( 'voteEvenement' )->setAttribute('value',$pendingParticipating->vote) ).'&nbsp;'; echo $this->formRow ( $form->get ( 'submit' ));?></td>
				</tr>
				<?php 
			endforeach; 
			echo $this->form()->closeTag();
			?>
		</table>
		<?php
		if ($nbEvtEnAttente > $nbLimit) {
			?>
			<p class="table">
				<a class="btn btn-plus btn-small pull-right" href="<?php echo $this->url('activity', array('action'=>'listPendingParticipating'));?>">
		<?php echo $this->translate("Plus d'&eacutev&eacutenements en attente") ?> &raquo;
	</a>
			</p>
			<?php
		}
		?>
		
		<br>
		<h1>Mes groupes</h1>
		<table class="table">
			<?php
			foreach ( $groupsLimit as $group ) :
				?>
				<tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
					<td>
						<a href="<?php echo $this->url('group', array('action'=>'details', 'id' => $group->id_group));?>" >
							<?php echo $this->escapeHtml($group->label);?>
						</a>
					</td>
				</tr>
			<?php endforeach; ?>
		</table>
		<?php
		if ($nbGroups > $nbLimit) {
			?>
			<p class="table">
				<a class="btn btn-plus btn-small pull-right" href="<?php echo $this->url('group', array('action'=>'index'));?>">
					<?php echo $this->translate("Plus de groupes") ?> &raquo;
				</a>
			</p>
			<?php
		}
		?>
	</div>
</div>