<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Qvm\Module'                        => __DIR__ . '/Module.php',
    'Qvm\Controller\IndexqvmController' => __DIR__ . '/src/Qvm/Controller/IndexqvmController.php',
	'Qvm\Controller\GroupController' => __DIR__ . '/src/Qvm/Controller/GroupController.php',
    'QvmTest\Framework\TestCase'        => __DIR__ . '/tests/Qvm/Framework/TestCase.php',
    'QvmTest\SampleTest'                => __DIR__ . '/tests/Qvm/SampleTest.php',
);
