<h1>Groupe " <?php echo $group->label;?> "</h1>

<div class="row-fluid">
	<div class="span6">
		<h2>Liste des membres</h2>
		<table class="table">
			<?php
			foreach ( $membres as $index => $membre ) : 
					?>
					 <tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
						<td>
							<?php echo $this->escapeHtml($membre->firstname).'&nbsp;'; 
							echo $this->escapeHtml($membre->surname).'&nbsp';?>
							<span class="pull-right">
								<?php 
									if ($this->escapeHtml($membre->is_sysadmin) == 1){
										echo 'Administrateur du groupe';
									}
								?>
							</span>
							<div class="decalage-droite">
								<?php 
									echo 'Mail : '.$this->escapeHtml($membre->mail).'<br/>';
									if (isset($membre->phonenumber)){
										echo 'Num&eacute;ro de t&eacute;l&eacute;phone : 	'.$this->escapeHtml($membre->phonenumber).'<br/>';
									}
									if ($this->escapeHtml($membre->is_sysadmin) == 1){
										echo 'Administrateur du groupe';
									}
								?>
							</div>
						</td>
					</tr>
					<?php 
			endforeach; 
			?>
		</table>
	</div>
</div>