<h1>Invitations aux groupes priv&eacute;s</h1>

<div class="row-fluid">
	<div class="span9">
		<table class="table">
		<?php 
		foreach ( $groupsPrivate as $groupPrivate ) :
			?>
		<tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
			<td>
				<?php echo $this->escapeHtml($groupPrivate->label);?>
				<span class="pull-right">
					<a href="<?php echo $this->url('group', array('action'=>'majGroupsPrivateInvit'));?>">
						<i class="icon-ok-sign"></i>
					</a>
					<a href="#">
						<i class="icon-remove-sign"></i>
					</a>
				</span>
			</td>
		</tr>
		<?php endforeach; ?>
		</table>


		<h1>Liste des groupes publiques</h1>

		<table class="table">
		<?php 
		foreach ( $groups as $group ) :
			?>
		<tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
			<td>
				<a href="<?php echo $this->url('group', array('action'=>'details', 'id' => $group->id_group));?>" >
					<?php echo $this->escapeHtml($group->label);?>
				</a>
				<span class="pull-right">
					<a href="#">
						Rejoindre
					</a>
				</span>
			</td>
		</tr>
		<?php endforeach; ?>
		</table>
	</div>
</div>
