<?php echo $this->doctype(); ?>

<html>
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('QVM')->setSeparator(' - ')->setAutoEscape(false)?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>

        <!-- Le styles -->
        <?php
								
								echo $this->headLink(/*array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico')*/)->prependStylesheet ( $this->basePath () . '/css/bootstrap-responsive.min.css' )->prependStylesheet ( $this->basePath () . '/css/style.css' )->prependStylesheet ( $this->basePath () . '/css/jquery-ui.css' )->prependStylesheet ( $this->basePath () . '/css/bootstrap.min.css' )?>

        <!-- Scripts -->
        <?php
								
								echo $this->headScript ()->prependFile ( $this->basePath () . '/js/html5.js', 'text/javascript', array (
										'conditional' => 'lt IE 9' 
								) )->prependFile ( $this->basePath () . '/js/bootstrap.min.js' )->prependFile($this->basePath () . '/js/jquery-ui.js')->prependFile($this->basePath () . ' /js/jquery.ui.datepicker-fr.js')->prependFile ( $this->basePath () . '/js/jquery.min.js' )->prependFile ( $this->basePath () . '/js/utils.js' )->prependFile($this->basePath () . '/js/jquery-1.9.1.min.js')?>

								
    </head>
<body>
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="brand" href="<?php echo $this->url('home') ?>"><?php echo 'Qui vient manger ?' ?></a>
					<?php
						if($this->url() != $this->url('user', array('action' => 'login'))){
					?>
					<div class="nav-collapse collapse">
						<ul class="nav">
							<li><a
								href="<?php echo $this->url('indexqvm', array('action' => 'index')) ?>"><?php echo 'Accueil' ?></a></li>
							<!-- Menu deroulant des groupes -->
							<li class="dropdown"><a href="#" class="dropdown-toggle"
								data-toggle="dropdown" title="Acces aux groupes"> Groupes <b
									class="caret"></b>
							</a>
								<ul class="dropdown-menu">
									<li><a
										href="<?php echo $this->url('group', array('action' => 'index')) ?>"><?php echo 'Mes groupes' ?></a></li>
									<li><a
										href="<?php echo $this->url('group', array('action' => 'create')) ?>"><?php echo 'Cr&eacuteer un groupe' ?></a></li>
								</ul></li>
							<!-- Menu deroulant des activites -->
								<li class="dropdown"><a href="#" class="dropdown-toggle"
								data-toggle="dropdown" title="Acces aux activites"> Activit&eacutes <b
									class="caret"></b>
							</a>
								<ul class="dropdown-menu">
									<li><a
										href="<?php echo $this->url('activity', array('action' => 'index')) ?>"><?php echo 'Mes activit&eacutes' ?></a></li>
									<li><a
										href="<?php echo $this->url('activity', array('action' => 'create')) ?>"><?php echo 'Cr&eacuteer une activit&eacute' ?></a></li>
								</ul></li>
						<!-- Menu deroulant de l'utilisateur-->
								<li class="dropdown"><a href="#" class="dropdown-toggle"
								data-toggle="dropdown" title="Parametres de l'utilisateur"> Mon compte <b
									class="caret"></b>
							</a>
								<ul class="dropdown-menu">
									<li><a
										href="<?php echo $this->url('user', array('action' => 'settings')) ?>"><?php echo 'Param&egravetres' ?></a></li>
									<li><a
										href="<?php echo $this->url('user', array('action' => 'logout')) ?>"><?php echo 'D&eacuteconnexion' ?></a></li>
								</ul></li>
						</ul>
						<?php } ?>
					</div>
				</div>
			</div>
		</div>
		
		<div class="container">
			<div class="fil-ariane">
				<?php
		       	    echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0);
				?>
			</div>
			
			<div class="row-fluid">
				<div class="span9">
	            	<?php echo $this->content; ?>
	            </div>
				<?php
				if($this->url() != $this->url('user', array('action' => 'login'))){
				?>
	            	<div class="span3" id="datepicker"></div>
	        	<?php } ?>
	            <hr class="invisible">
	            <hr class="invisible">
	            <hr>
	        </div> 
	    
	<footer>
		<div class="container">
			<p class="muted credit">
				Margot Bernard / Antoine Dumas / Sebastien
				Gendreau / Cedric Bouygues
			</p>
		</div>
	</footer>
	</div>
        
	
	<!-- /container -->
        <?php echo $this->inlineScript()?>
    </body>
</html>
