<?php if ($this->pageCount): ?>
<div class="pagination">
<ul>
  <!-- Previous page link -->
  <?php if (isset($this->previous)): ?>
    <li>
      <a href="<?php echo $this->url($this->route, array('page' => $this->previous, 'id' => $this->id)); ?>">&larr; Pr&eacutec&eacutedent</a>
    </li>
  <?php else: ?>
    <li class="disabled"><a>&larr; Pr&eacutec&eacutedent</a></li>
  <?php endif; ?>
  
  <!-- Numbered page links -->
  <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
      <li>
        <a href="<?php echo $this->url($this->route, array('page' => $page, 'id' => $this->id)); ?>">
          <?php echo $page; ?>
        </a>
      </li>
    <?php else: ?>
      <li class="active"><a><?php echo $page; ?></a></li>
    <?php endif; ?>
  <?php endforeach; ?>
  
  <!-- Next page link -->
  <?php if (isset($this->next)): ?>
    <li>
      <a href="<?php echo $this->url($this->route, array('page' => $this->next, 'id' => $this->id)); ?>">Suivant &rarr;</a>
    </li>
  <?php else: ?>
    <li class="disabled"><a>Suivant &rarr;</a></li>
  <?php endif; ?>
  </ul>
</div>
<?php endif; ?>