<?php
use Zend\I18n\View\Helper\DateFormat;
$form = $this->form;
echo $this->form ()->openTag ( $form );
?>
<h1>Activit&eacute "<?php echo $this->escapeHtml($activity->title);?>" - Ev&eacutenement du 

<?php
echo $this->dateFormat(
    new DateTime($event->date),
    IntlDateFormatter::FULL, // date
    IntlDateFormatter::SHORT // time
);
?>
</h1>
<table class="table">
	<td><?php echo $this->formRow ( $form->get ( 'voteEvenement' )->setAttribute('value',$event->vote) );?></td>
	<td><?php echo $this->formRow ( $form->get ( 'submit' ));?></td>
</table>

<h2>Liste des participants</h2>
<table class="table">
<?php foreach ($persons as $person) :?>
 <tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
		<td><?php echo $this->escapeHtml($person->firstname);?></td>
		<td><?php echo $this->escapeHtml($person->surname);?></td>
		<td><?php echo $this->formRow ( $form->get ( 'voteEvenement' )->setAttribute('value',$person->vote)->setAttribute('disabled','disabled') );?></td>
	</tr>	
<?php endforeach; ?>
</table>
<?php echo $this->paginationControl($this->persons, 'Elastic', 'pagination', array('route' => 'paginationActivityDetailEvent/page', 'id' => $event->id_event)); ?>

<h2>Commentaires</h2>
<table class="table">
<?php foreach ($comments as $comment) :?>
 <tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
		<td><?php echo $this->escapeHtml($comment->id_person);?> - 
	<?php
	echo $this->dateFormat(
    new DateTime($comment->datetime),
    IntlDateFormatter::SHORT, // date
    IntlDateFormatter::SHORT // time
);
?></td>
		<td><?php echo $this->escapeHtml($comment->body);?></td>
	</tr>	
<?php endforeach; ?>
</table>