<?php
$form = $this->form;
echo $this->form ()->openTag ( $form );
?>
<h1>Activit&eacute "<?php echo $this->escapeHtml($activity->title);?>" - Ev&eacutenement du <?php echo $this->escapeHtml($event->date);?></h1>

<table class="table">
	<td><?php echo $this->formRow ( $form->get ( 'voteEvenement' )->setAttribute('value',$event->vote) );?></td>
	<td><?php echo $this->formRow ( $form->get ( 'submit' ));?></td>
</table>

<h2>Liste des participants</h2>
<table class="table">
</table>

<h2>Commentaires</h2>
<table class="table">
<?php foreach ($comments as $comment) :?>
 <tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
		<td><?php echo $this->escapeHtml($comment->id_person);?> - <?php echo $this->escapeHtml($comment->datetime);?></td>
		<td><?php echo $this->escapeHtml($comment->body);?></td>
	</tr>	
<?php endforeach; ?>
</table>