<?php
$form = $this->form;
echo $this->form ()->openTag ( $form );

$formComment = $this->formComment ;
$formComment->prepare();
$formComment->setAttribute('action', $this->url('activity', array('action' => 'detail-event', 'event' => $event)));
$formComment->setAttribute('method', 'post');
echo $this->form()->openTag($formComment);

?>
<h1>Activit&eacute "<?php echo $this->escapeHtml($activity->title);?>" - Ev&eacutenement du 
<?php echo date('d/m/Y H\hi', strtotime($event->date)); ?>
</h1>
<table class="table">
	<td class="width310"><?php echo $this->formRow ( $form->get ( 'voteEvenement' )->setAttribute('value',$event->vote) );?></td>
	<td><?php echo $this->formRow ( $form->get ( 'submit' ));?></td>
</table>

<h2>Liste des participants</h2>
<table class="table">
<?php foreach ($persons as $person) :?>
 <tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
		<td><?php echo $this->escapeHtml($person->firstname);?></td>
		<td><?php echo $this->escapeHtml($person->surname);?></td>
		<td><?php echo $this->formRow ( $form->get ( 'voteEvenement' )->setAttribute('value',$person->vote)->setAttribute('disabled','disabled') );?></td>
	</tr>	
<?php endforeach; ?>
</table>
<?php echo $this->paginationControl($this->persons, 'Elastic', 'pagination', array('route' => 'paginationActivityDetailEvent/page', 'id' => $event->id_event)); ?>

<h2>Commentaires</h2>
<table class="table">
<?php foreach ($comments as $comment) :?>
 <tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
		<td><?php echo $this->escapeHtml($comment->user_id);?> - 
	<?php echo date('d/m/Y H\hi', strtotime($comment->datetime)); ?>
		<td><?php echo $this->escapeHtml($comment->body);?></td>
	</tr>	
<?php endforeach; ?>
</table>
		
<dl class="zend_form">
	<dd><?php echo $this->formRow ( $formComment->get ( 'body' ) );?></dd>
	<dd><?php echo $this->formSubmit ( $formComment->get ( 'submit' ) );?></dd>
</dl>