<h1>Mes Activit&eacutes</h1>


<table class="table">
<?php 
foreach ($activites as $activity) :
	?>
<tr>
	<td>
		<a href="<?php echo $this->url('activity', array('action'=>'details', 'id' => $activity->id_activity));?>" >
			<?php echo $this->escapeHtml($activity->description);?>
		</a>
	</td>
</tr>
<?php endforeach; ?>
</table>
<?php
if ($nbActivites > 10) {
	?>
<p>
	<a class="btn btn-success btn-small" href="#"><?php echo $this->translate("Plus d'activit&eacutes") ?> &raquo;</a>
</p>
<?php

}
?>
