<?php
$form = $this->form;
echo $this->form ()->openTag ( $form );
?>
<h1>Mes &eacutev&eacutenements en attente de vote</h1>
<table class="table">
<?php 
foreach ($events as $event) :
	?>
<tr class="<?php echo $this->cycle(array('liste-grise','liste-blanche'))->next()?>">
		<td><?php echo $this->escapeHtml($event->title);?></td>
		<td><a href="<?php echo $this->url('activity', array('action'=>'detailEvent', 'id' => $event->id_event));?>" >
			<?php  echo strftime("%d/%m/%Y a %Hh%M", strtotime($event->date) ); ?></a>
		</td>
		<td><?php echo $this->formRow ( $form->get ( 'voteEvenement' )->setAttribute('value',$event->vote) );?></td>
		<td><?php echo $this->formRow ( $form->get ( 'submit' ));?></td>
</tr>
<?php endforeach; ?>
</table>

<?php echo $this->paginationControl($this->events, 'Elastic', 'pagination', array('route' => 'paginationActivityListPendingParticipating/page')); ?>